[platformio]
default_envs = native_core2

[env:native_core2]
platform = native
build_type = debug
build_flags = 
  -O0 -xc++ -std=c++14 -lSDL2
  -arch arm64
  -I/opt/homebrew/include/SDL2
  -L/opt/homebrew/lib
  -DM5GFX_SHOW_FRAME
  -DM5GFX_BOARD=board_M5StackCore2
  -DM5GFX_SCALE=2
  -DM5GFX_BACK_COLOR=0x111827u
  -I../../
lib_extra_dirs = 
  /Users/david/Documents/Arduino/libraries
